import { useEffect, useState, type FormEvent } from 'react';
import { api, errorMessage, post } from './api';
import { Busy, Empty, Icon, Notice, PageHeading, StateBadge } from './components';
import { dateLabel } from './presentation';
import type { AuthConfig, AuthProvider, Capabilities, Improvement, User } from './types';

export function ImprovementsPage() {
  const [items, setItems] = useState<Improvement[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => {
    let alive = true;
    api<Improvement[]>('/improvements').then(value => { if (alive) setItems(value); }).catch(cause => { if (alive) setError(errorMessage(cause)); }).finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, []);
  return <><PageHeading title="Mejoras de Roboti">De una diferencia documentada a una propuesta verificable. Ninguna observación modifica reglas automáticamente.</PageHeading>
    <Notice><strong>Revisión y evidencia antes de aplicar cambios.</strong> Las propuestas se registran desde un hallazgo del paciente. La causa debe investigarse; los ajustes a un origen DALIA no prueban un error de Roboti.</Notice>
    <div className="proposal-flow"><span><b>1</b> Evidencia</span><Icon name="arrow" /><span><b>2</b> Revisión del auditor</span><Icon name="arrow" /><span><b>3</b> Propuesta registrada</span><Icon name="arrow" /><span className="future-step"><b>4</b> Validación técnica futura</span></div>
    {error && <Notice tone="danger">{error}</Notice>}<section className="surface-card"><h2>Propuestas de mejora</h2>{loading ? <Busy /> : !items.length ? <Empty title="Aún no hay propuestas registradas">En el detalle de un paciente, abre «Ver evidencia» y selecciona «Proponer mejora» para vincular el cambio a su documentación.</Empty> : <div className="proposal-list">{items.map(item => <article className="proposal-item" key={item.id}><div className="section-toolbar"><a href={`#/runs/${item.run_id}/${item.case_id}`}>Ver paciente y evidencia ↗</a><span className="state-badge badge-warning">{item.status === 'approved' ? 'Aprobada para análisis · sin despliegue automático' : 'Pendiente de análisis técnico'}</span></div><h3>Problema documental / cambio propuesto</h3><p className="evidence-text">{item.description}</p><h3>Beneficio esperado y verificación</h3><p className="evidence-text">{item.expected_benefit}</p><small className="text-secondary">Registrada: {dateLabel(item.created_at)} · Referencia {item.id.slice(0, 8)}</small></article>)}</div>}</section>
  </>;
}

export function UsersPage({ authConfig = { provider: 'local', password_management: 'local' }, authProvider }: { authConfig?: AuthConfig; authProvider?: AuthProvider }) {
  const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const external = authConfig.provider === 'aitrol' || authConfig.password_management === 'aitrol' || authProvider === 'aitrol';
  const reload = async () => setUsers(await api<User[]>('/users'));
  useEffect(() => { let alive = true; api<User[]>('/users').then(value => { if (alive) setUsers(value); }).catch(cause => { if (alive) setError(errorMessage(cause)); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (external) { setError('La creación de usuarios y las contraseñas se gestionan en Aitrol.'); return; }
    const form = event.currentTarget; const fields = new FormData(form); setBusy(true); setError(''); setMessage('');
    try { await post('/users', { username: fields.get('username'), password: fields.get('password'), role: fields.get('role') }); form.reset(); await reload(); setMessage('Usuario creado en tu organización. Entrega el acceso mediante un canal seguro.'); }
    catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); }
  };
  return <><PageHeading title="Usuarios y permisos">Acceso administrado por organización. No existe registro público.</PageHeading>{error && <Notice tone="danger">{error}</Notice>}{message && <Notice tone="success">{message}</Notice>}
    {external && <Notice><strong>Consulta de usuarios sincronizados con Aitrol.</strong> Las altas de usuarios, los cambios y la recuperación de contraseñas se gestionan en Aitrol. CompareForms no crea cuentas ni modifica esas contraseñas desde este portal.</Notice>}
    <div className="row g-4"><div className={external ? 'col-12' : 'col-xl-7'}><section className="surface-card"><h2>Usuarios de la organización</h2>{loading ? <Busy /> : <div className="table-responsive"><table className="table audit-table"><thead><tr><th>{external ? 'Correo / usuario' : 'Usuario'}</th><th>Rol en CompareForms</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.username}</strong></td><td>{{ auditor: 'Auditor', supervisor: 'Supervisor', admin: 'Administrador' }[user.role]}</td></tr>)}</tbody></table></div>}</section></div>{!external && <div className="col-xl-5"><section className="surface-card"><h2>Crear usuario</h2><form onSubmit={create}><label className="form-label mt-3" htmlFor="new-username">Usuario</label><input className="form-control" id="new-username" name="username" autoComplete="off" required minLength={3} maxLength={100} /><label className="form-label mt-3" htmlFor="new-password">Contraseña inicial</label><input className="form-control" id="new-password" name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={128} /><p className="form-text">Mínimo 12 caracteres. No reutilices la contraseña de otros sistemas.</p><label className="form-label" htmlFor="new-role">Rol</label><select className="form-select" id="new-role" name="role" defaultValue="auditor"><option value="auditor">Auditor · cargar, comparar y revisar</option><option value="supervisor">Supervisor · revisar y consultar evolución</option><option value="admin">Administrador · gestionar usuarios</option></select><button className="btn btn-primary mt-4" disabled={busy}>{busy ? 'Creando usuario…' : 'Crear usuario'}</button></form></section></div>}</div>
  </>;
}

export function ModelsPage({ capabilities }: { capabilities: Capabilities | null }) {
  return <><PageHeading title="Modelos y evolución futura">La comparación funcional utiliza reglas verificables y asociación global de costo mínimo.</PageHeading><div className="row g-4"><div className="col-xl-7"><section className="surface-card model-current"><span className="state-badge badge-success">Opción A · motor de comparación</span><h2 className="mt-3">Mínimo error, con evidencia</h2><p>La comparación relaciona páginas, identifica incorporaciones, retiradas y cambios, y conserva la evidencia antes/después. La revisión humana permite registrar falsos positivos y diferencias omitidas.</p><ul className="model-list"><li>La reducción de diferencias no es el objetivo: lo es reducir omisiones y asociaciones incorrectas.</li><li>Los resultados ilegibles o ambiguos se remiten a revisión; no se declaran iguales.</li><li>La información del paciente y los números de página no se inventan.</li></ul></section></div><div className="col-xl-5"><section className="surface-card model-future"><span className="state-badge badge-neutral">Opción B · arquitectura reservada</span><h2 className="mt-3">Encoder-decoder</h2><div className="model-count">{capabilities ? capabilities.ml.unique_pdf_count.toLocaleString('es-EC') : '—'}<small> PDF únicos registrados</small></div><p className="model-threshold">Condición inicial: superar {capabilities?.ml.threshold ?? 1000} PDF únicos.</p><Notice tone="warning">{capabilities?.ml.reason || 'El modelo no está generado ni entrenado. La disponibilidad y calidad del corpus se evaluarán en una fase posterior.'}</Notice><p className="form-text">Superar el umbral no inicia entrenamiento. Se requiere autorización, registros adjudicados, separación por paciente y validación independiente contra el motor A.</p><button className="btn btn-outline-secondary w-100" disabled>Entrenamiento no habilitado</button></section></div></div></>;
}
